//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string id { get; set; }
        public string role_name { get; set; }

        public static explicit operator Role(string v)
        {
            throw new NotImplementedException();
        }
    }
}
